services:
  client:
    command: 'npm run prod'
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    networks:
      - welbex-network
  server:
    command: 'npm run start'
    build: ./server
    restart: unless-stopped
    networks:
      - welbex-network
    depends_on:
      - database
    environment:
      - PORT=3000
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST=database
      - POSTGRES_DATABASE=welbex
      - POSTGRES_PORT=5432
  database:
    build: ./database
    environment:
      - POSTGRES_PASSWORD=root

networks:
  welbex-network:
    driver: bridge
