services:
  client:
    command: 'npm run start'
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client/src:/usr/src/app/src
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - welbex-network
  server:
    command: 'npm run dev'
    build: ./server
    volumes:
      - ./server/src:/usr/src/app/src
    restart: unless-stopped
    networks:
      - welbex-network
    depends_on:
      database:
        condition: service_healthy
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST=database
      - POSTGRES_DATABASE=welbex
      - POSTGRES_PORT=5432
  database:
    build: ./database
    networks:
      - welbex-network
    environment:
      - POSTGRES_PASSWORD=root
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 3s
      timeout: 3s

networks:
  welbex-network:
    driver: bridge
